[torizon]
url = "https://dgw.torizon.io/ras/"
server_cert_path = "/usr/lib/sota/root.crt"
client_cert_path = "/var/sota/import/client.pem"
client_key_path = "/var/sota/import/pkey.pem"

[device]
# If this file does not exist, a new key will be generated and saved to this file
ssh_private_key_path = "/home/torizon/run/rac/device-key-01.sec"
unprivileged_user_group = "torizon:torizon"
local_tuf_repo_path = "/home/torizon/run/rac/uptane-repo"

[device.session.spawned_sshd]
sshd_path = "/usr/sbin/sshd"
config_dir = "/home/torizon/run/rac"
